export const dummyCompetitions = [
  {
    id: '1',
    name: '주말 등산 모임 ⛰️',
    start_date: '23-09-08',
    end_date: '23-11-08',
    current_members: 19,
    max_members: 20,
    tags: ['등산', '랭킹전'],
  },
  {
    id: '2',
    name: '한강 러닝 크루 모집합니다',
    start_date: '23-09-14',
    end_date: '23-10-14',
    current_members: 2,
    max_members: 2,
    tags: ['러닝', '다이어트', '1:1'],
  },
  {
    id: '3',
    name: '스쿼트 챌린지 들어오세요!',
    start_date: '23-09-15',
    end_date: '23-10-15',
    current_members: 8,
    max_members: 10,
    tags: ['다이어트', '웨이트', '랭킹전'],
  },
  {
    id: '4',
    name: '점심 산책 1시간 🌿',
    start_date: '23-09-20',
    end_date: '23-10-20',
    current_members: 5,
    max_members: 5,
    tags: ['걷기', '다이어트', '랭킹전'],
  },
  {
    id: '5',
    name: '아침 수영 1km 🏊‍♀️',
    start_date: '23-09-03',
    end_date: '23-10-03',
    current_members: 1,
    max_members: 2,
    tags: ['다이어트', '1:1'],
  },
  {
    id: '6',
    name: '한 달 동안 매일 줄넘기',
    start_date: '23-09-22',
    end_date: '23-10-22',
    current_members: 8,
    max_members: 10,
    tags: ['다이어트', '웨이트', '랭킹전'],
  },
  {
    id: '7',
    name: '30일 플랭크 도전!!!!',
    start_date: '23-08-20',
    end_date: '23-09-20',
    current_members: 4,
    max_members: 5,
    tags: ['웨이트', '다이어트', '랭킹전'],
  },
  {
    id: '8',
    name: '아침 요가 챌린지',
    start_date: '23-09-18',
    end_date: '23-10-18',
    current_members: 4,
    max_members: 5,
    tags: ['다이어트', '랭킹전'],
  },
  {
    id: '9',
    name: '매일 5km 달리기 🏃‍♂️',
    start_date: '23-09-01',
    end_date: '23-10-01',
    current_members: 2,
    max_members: 2,
    tags: ['러닝', '1:1'],
  },
  {
    id: '10',
    name: '주말마다 등산하기',
    start_date: '23-09-10',
    end_date: '23-11-10',
    current_members: 3,
    max_members: 5,
    tags: ['등산', '걷기', '랭킹전'],
  },
  {
    id: '11',
    name: '30일 플랭크 도전!!!!',
    start_date: '23-08-25',
    end_date: '23-09-25',
    current_members: 2,
    max_members: 2,
    tags: ['웨이트', '1:1'],
  },
  {
    id: '12',
    name: '아침 스쿼트 100개',
    start_date: '23-09-05',
    end_date: '23-10-05',
    current_members: 7,
    max_members: 10,
    tags: ['웨이트', '다이어트', '랭킹전'],
  },
  {
    id: '13',
    name: '엘베 대신 계단 오르기',
    start_date: '23-08-30',
    end_date: '23-09-30',
    current_members: 3,
    max_members: 5,
    tags: ['걷기', '다이어트', '랭킹전'],
  },

  {
    id: '14',
    name: '주 3회 헬스장 가기',
    start_date: '23-09-12',
    end_date: '23-10-12',
    current_members: 1,
    max_members: 2,
    tags: ['웨이트', '1:1'],
  },

  {
    id: '15',
    name: '실내 사이클링 챌린지',
    start_date: '23-09-25',
    end_date: '23-10-25',
    current_members: 12,
    max_members: 20,
    tags: ['다이어트', '랭킹전'],
  },

  {
    id: '16',
    name: '30일 버피 챌린지 하실 분',
    start_date: '23-09-28',
    end_date: '23-10-28',
    current_members: 6,
    max_members: 10,
    tags: ['웨이트', '다이어트', '랭킹전'],
  },
  {
    id: '17',
    name: '매일 팔굽혀펴기 50개',
    start_date: '23-09-07',
    end_date: '23-10-07',
    current_members: 2,
    max_members: 2,
    tags: ['웨이트', '1:1'],
  },

  {
    id: '18',
    name: '주 5회 스트레칭 하기',
    start_date: '23-09-19',
    end_date: '23-10-19',
    current_members: 7,
    max_members: 10,
    tags: ['다이어트', '랭킹전'],
  },
  {
    id: '19',
    name: '매일 1만보 걷기',
    start_date: '23-09-11',
    end_date: '23-10-11',
    current_members: 16,
    max_members: 20,
    tags: ['걷기', '다이어트', '랭킹전'],
  },
  {
    id: '20',
    name: '주 3회 10km 달리기',
    start_date: '23-09-21',
    end_date: '23-10-21',
    current_members: 1,
    max_members: 2,
    tags: ['러닝', '1:1'],
  },
];

export const dummyMyCompetitions = [
  {
    id: '1',
    name: '스쿼트 챌린지 들어오세요!',
    start_date: '23-08-01',
    end_date: '23-09-01',
    current_members: 3,
    max_members: 10,
    tags: ['다이어트', '웨이트', '랭킹전'],
  },
  {
    id: '2',
    name: '매일 5km 달리기 🏃‍♂️',
    start_date: '23-09-01',
    end_date: '23-10-01',
    current_members: 2,
    max_members: 2,
    tags: ['러닝', '걷기', '랭킹전'],
  },
  {
    id: '4',
    name: '주말마다 등산하기 ⛰️',
    start_date: '23-09-01',
    end_date: '23-10-01',
    current_members: 2,
    max_members: 2,
    tags: ['등산', '걷기', '1:1'],
  },
];
