export const dummyFriends = [
  { id: '1', nickname: '헬짱', introduce: '운동을 좋아해요', preferred_sport: '웨이트', profile_image: null },
  {
    id: '2',
    nickname: '등산러',
    introduce: '등산등산',
    preferred_sport: '등산',
    profile_image: 'https://avatar.iran.liara.run/public/77',
  },
  {
    id: '3',
    nickname: '여름싫어',
    introduce: '같이 달려요!',
    preferred_sport: '러닝',
    profile_image: 'https://avatar.iran.liara.run/public/48',
  },
  {
    id: '4',
    nickname: '올라운더',
    introduce: '다양한 운동을 즐겨요',
    preferred_sport: '웨이트',
    profile_image: 'https://avatar.iran.liara.run/public/25',
  },
  {
    id: '5',
    nickname: '헬린이',
    introduce: '',
    preferred_sport: '다이어트',
    profile_image: null,
  },
  {
    id: '6',
    nickname: '여름싫어',
    introduce: '같이 달려요!',
    preferred_sport: '걷기',
    profile_image: null,
  },
  {
    id: '7',
    nickname: '올라운더',
    introduce: '다양한 운동을 즐겨요',
    preferred_sport: '웨이트',
    profile_image: null,
  },
  {
    id: '8',
    nickname: '수영왕',
    introduce: '수영과 자전거를 좋아해요',
    preferred_sport: '수영',
    profile_image: null,
  },
];
