export const dummyCompetitions = [
  {
    id: '1',
    name: '스쿼트 챌린지 들어오세요!',
    start_date: '23.08.01',
    end_date: '23.09.01',
    current_members: 3,
    max_members: 10,
    tags: ['다이어트', '웨이트트레이닝', '랭킹전'],
  },
  {
    id: '2',
    name: '30일 플랭크 도전!!!!',
    start_date: '23.08.15',
    end_date: '23.09.15',
    current_members: 5,
    max_members: 8,
    tags: ['웨이트트레이닝', '다이어트', '1:1'],
  },
  {
    id: '3',
    name: '매일 5km 달리기 🏃‍♂️',
    start_date: '23.09.01',
    end_date: '23.10.01',
    current_members: 2,
    max_members: 2,
    tags: ['러닝', '걷기', '랭킹전'],
  },
  {
    id: '4',
    name: '주말마다 등산하기 ⛰️',
    start_date: '23.09.01',
    end_date: '23.10.01',
    current_members: 2,
    max_members: 2,
    tags: ['등산', '걷기', '1:1'],
  },
  {
    id: '5',
    name: '30일 플랭크 도전!!!!',
    start_date: '23.08.15',
    end_date: '23.09.15',
    current_members: 2,
    max_members: 2,
    tags: ['웨이트트레이닝', '1:1'],
  },
  {
    id: '6',
    name: '스쿼트 챌린지 들어오세요!',
    start_date: '23.08.01',
    end_date: '23.09.01',
    current_members: 3,
    max_members: 10,
    tags: ['다이어트', '웨이트트레이닝', '랭킹전'],
  },
  {
    id: '7',
    name: '30일 플랭크 도전!!!!',
    start_date: '23.08.15',
    end_date: '23.09.15',
    current_members: 5,
    max_members: 8,
    tags: ['웨이트트레이닝', '랭킹전'],
  },
  {
    id: '8',
    name: '스쿼트 챌린지 들어오세요!',
    start_date: '23.08.01',
    end_date: '23.09.01',
    current_members: 3,
    max_members: 10,
    tags: ['다이어트', '웨이트트레이닝', '랭킹전'],
  },
  {
    id: '9',
    name: '매일 5km 달리기 🏃‍♂️',
    start_date: '23.09.01',
    end_date: '23.10.01',
    current_members: 2,
    max_members: 15,
    tags: ['러닝', '1:1'],
  },
];
